<?php
    include 'includes/header.php';
    require 'includes/menu.php';

    // We'll make the assumption that the user will always
    // upload an image that is sized similarly to an album cover
    if (isset($_POST['submit'])) {
        require_once '../../../mysqli_connect.php';
        $username = $_SESSION['username'];
        $errors = 0;

        if (empty($_FILES['cover1']['name'])) {
            $errors = 1;
        } else {
            $images['cover1'] = htmlspecialchars($_FILES['cover1']['name']);
        }
        if (empty($_FILES['cover2']['name'])) {
            $errors = 1;
        } else {
            $images['cover2'] = htmlspecialchars($_FILES['cover2']['name']);
        }
        if (empty($_FILES['cover3']['name'])) {
            $errors = 1;
        } else {
            $images['cover3'] = htmlspecialchars($_FILES['cover3']['name']);
        }
        if (empty($_FILES['cover4']['name'])) {
            $errors = 1;
        } else {
            $images['cover4'] = htmlspecialchars($_FILES['cover4']['name']);
        }

        if (empty($_POST['title1'])) {
            $errors = 1;
        } else {
            $title1 = filter_var(trim($_POST['title1']), FILTER_SANITIZE_FULL_SPECIAL_CHARS, FILTER_FLAG_NO_ENCODE_QUOTES);
        }
        if (empty($_POST['title2'])) {
            $errors = 1;
        } else {
            $title2 = filter_var(trim($_POST['title2']), FILTER_SANITIZE_FULL_SPECIAL_CHARS, FILTER_FLAG_NO_ENCODE_QUOTES);
        }
        if (empty($_POST['title3'])) {
            $errors = 1;
        } else {
            $title3 = filter_var(trim($_POST['title3']), FILTER_SANITIZE_FULL_SPECIAL_CHARS, FILTER_FLAG_NO_ENCODE_QUOTES);;
        }
        if (empty($_POST['title4'])) {
            $errors = 1;
        } else {
            $title4 = filter_var(trim($_POST['title4']), FILTER_SANITIZE_FULL_SPECIAL_CHARS, FILTER_FLAG_NO_ENCODE_QUOTES);;
        }

        if (empty($_POST['artist1'])) {
            $errors = 1;
        } else {
            $artist1 = filter_var(trim($_POST['artist1']), FILTER_SANITIZE_FULL_SPECIAL_CHARS, FILTER_FLAG_NO_ENCODE_QUOTES);
        }
        if (empty($_POST['artist2'])) {
            $errors = 1;
        } else {
            $artist2 = filter_var(trim($_POST['artist2']), FILTER_SANITIZE_FULL_SPECIAL_CHARS, FILTER_FLAG_NO_ENCODE_QUOTES);
        }
        if (empty($_POST['artist3'])) {
            $errors = 1;
        } else {
            $artist3 = filter_var(trim($_POST['artist3']), FILTER_SANITIZE_FULL_SPECIAL_CHARS, FILTER_FLAG_NO_ENCODE_QUOTES);
        }
        if (empty($_POST['artist4'])) {
            $errors = 1;
        } else {
            $artist4 = filter_var(trim($_POST['artist4']), FILTER_SANITIZE_FULL_SPECIAL_CHARS, FILTER_FLAG_NO_ENCODE_QUOTES);
        }
        
        // postID will be automatically generated by the db
        $postID = 0;

        $query = "INSERT INTO A4Y_Posts VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        $stmt = mysqli_prepare($dbc, $query);
        mysqli_stmt_bind_param($stmt, 'isssssssssssss',
            $postID,
            $username,
            $images['cover1'],
            $images['cover2'],
            $images['cover3'],
            $images['cover4'],
            $title1,
            $artist1,
            $title2,
            $artist2,
            $title3,
            $artist3,
            $title4,
            $artist4 
        );
        
        mysqli_stmt_execute($stmt);

        // This try catch block helped me figure out an error where
        // I had to increase the varchar of some columns in satoshi
        // try {
        //     mysqli_stmt_execute($stmt);
        // } catch (Exception $e) {
        //     echo $e;
        // }

        if (mysqli_stmt_affected_rows($stmt)) {
            // Now uploading images...
            $lastID = mysqli_insert_id($dbc);

            // Creates the user's folder if it doesn't exist
            if (!is_dir('../a4y_uploads/$username')) {
                mkdir("../a4y_uploads/$username", 0777, true);
            }

            // Creates the directory for the post in the user's folder
            mkdir("../a4y_uploads/$username/$lastID", 0777, true);

            foreach ($_FILES as $file) {
                $targetDir = "../a4y_uploads/$username/$lastID/{$file['name']}";
                
                $check = getimagesize($file['tmp_name']);
                $maxSize = 1024*1024;
                // Checks to make sure that the file is an image and not larger than 1MB to maximize security
                if ($check && $file['size'] <= $maxSize) {
                    if (move_uploaded_file($file['tmp_name'], $targetDir)) {
                        // echo '<h6>The image ' . $file['name'] . ' has been uploaded successfully!</h6>';
                        continue;
                    }
                }
            }

            echo "<h1>Post made successfully!<h1><br>";
            echo "<h3>Check the home page to see your post!<h3>";
            exit;
        }
        if ($_FILES['site_img']['error'] > 0) {
		    echo '<p class="error">The file could not be uploaded because: <strong>';

			// Print a message based upon the error.
			switch ($_FILES['site_img']['error']) {
				case 1:
					echo 'The file exceeds the upload_max_filesize setting in php.ini.';
					break;
				case 2:
					echo 'The file exceeds the MAX_FILE_SIZE setting in the HTML form.';
					break;
				case 3:
					echo 'The file was only partially uploaded.';
					break;
				case 4:
					echo 'No file was uploaded.';
					break;
				case 6:
					echo 'No temporary folder was available.';
					break;
				case 7:
					echo 'Unable to write to the disk.';
					break;
				case 8:
					echo 'File upload stopped.';
					break;
				default:
					echo 'A system error occurred.';
					break;
			} // End of switch.
			echo '</strong></p>';
		} 
    }

?>
<form method="post" action="create_post.php" enctype="multipart/form-data">
    <fieldset>
        <legend>Create Post</legend>
        <fieldset class="album-input">
            <legend>Album 1</legend>
            <label class="input-title">Album
                <input type="text" name="title1">
            </label>
            <label class="input-artist">Artist
                <input type="text" name="artist1">
            </label>
            <label class="input-cover">Album Cover
                <input type="file" name="cover1" accept="image/*">
            </label>
        </fieldset>

        <fieldset class="album-input">
            <legend>Album 2</legend>
            <label class="input-title">Album
                <input type="text" name="title2">
            </label>
            <label class="input-artist">Artist
                <input type="text" name="artist2">
            </label>
            <label class="input-cover">Album Cover
                <input type="file" name="cover2" accept="image/*">
            </label>
        </fieldset>

        <fieldset class="album-input">
            <legend>Album 3</legend>
            <label class="input-title">Album
                <input type="text" name="title3">
            </label>
            <label class="input-artist">Artist
                <input type="text" name="artist3">
            </label>
            <label class="input-cover">Album Cover
                <input type="file" name="cover3" accept="image/*">
            </label>
        </fieldset>

        <fieldset class="album-input">
            <legend>Album 4</legend>
            <label class="input-title">Album
                <input type="text" name="title4">
            </label>
            <label class="input-artist">Artist
                <input type="text" name="artist4">
            </label>
            <label class="input-cover">Album Cover
                <input type="file" name="cover4" accept="image/*">
            </label>
        </fieldset>

        <input name="submit" id="post-submit" type="submit" value="Post">
    </fieldset>
</form>
<?php
    include 'includes/footer.php';
?>